version: '3.1'

services:

  mongo:
    image: mongo:4
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  mongo-seed:
    build: ./data
    environment:
      DATABASE: mongodb://mongo:27017/rickmorty-api
    depends_on:
      - mongo

  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      DATABASE: mongodb://mongo:27017/rickmorty-api
    depends_on:
      - mongo
      - mongo-seed
