version: '3.1'

services:

  mongo:
    image: mongo:4
    restart: always
    ports:
      - 127.0.0.1:27017:27017

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081

  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      DATABASE: mongodb://mongo:27017/rickmorty-api
    depends_on:
      - mongo
